//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedemySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teachers
    {
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherPassword { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherEmail { get; set; }
        public string TeacherPhoneNumber { get; set; }
        public byte TeacherGender { get; set; }
        public string TeacherAddress { get; set; }
        public string TeacherNationalCode { get; set; }
        public System.DateTime TeacherBirthDay { get; set; }
        public byte[] TeacherPicture { get; set; }
        public byte TeacherStatus { get; set; }
        public string TeacherCreateDate { get; set; }
        public string TeacherCreateTime { get; set; }
    }
}
