//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedemySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_ShowStudents
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentPassword { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPhoneNumber { get; set; }
        public string StudentNationalCode { get; set; }
        public string StudentAddress { get; set; }
        public System.DateTime StudentBirthDay { get; set; }
        public byte[] StudentPicture { get; set; }
        public string GenderStudent { get; set; }
        public string StatusStudent { get; set; }
        public string StudentCreateDate { get; set; }
        public string StudentCreateTime { get; set; }
    }
}
