//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedemySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_ShowAdmins
    {
        public int AdminID { get; set; }
        public string AdminName { get; set; }
        public string AdminPassword { get; set; }
        public string AdminFirstName { get; set; }
        public string AdminLastName { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPhoneNumber { get; set; }
        public string AdminNationalCode { get; set; }
        public string AdminAddress { get; set; }
        public System.DateTime AdminBirthDay { get; set; }
        public byte[] AdminPicture { get; set; }
        public string GenderAdmin { get; set; }
        public string StatusAdmin { get; set; }
        public string RoleAdmin { get; set; }
        public string AdminCreateDate { get; set; }
        public string AdminCreateTime { get; set; }
        public byte AdminRole { get; set; }
    }
}
